language: c++
os: linux
sudo: false

addons:
  apt:
    packages:
      - clang-3.7
      - libclang-3.7-dev
      - llvm-3.7-tools
      - libboost-dev
      - python-pip
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_CXX_COMPILER=clang++-3.7 -DCPACK_GENERATOR="TGZ;DEB" -DLIT_MODULE="/usr/lib/llvm-3.7/build/utils/lit/lit.py" ..
  - make all
  - make check
  - mkdir target_dir
  - DESTDIR=target_dir make install
  - make package
